# User config
author: "MATIAS"
tagline: "leotecnologia"
description: "en esta compania te aydamos en todo lo que se le nececite"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "Leonardojoel09mv@gmail.com"
linkedin: "leotecnologico.github.io"
twitter: "LEONARDO09"
github: "MATIAS-MIGUEL.GITHUB.IO"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
